%%The following function will allow us to represent a cylindrical figure
%%for each of the other codes, to be able to see, amognst the vectorial
%%representation, the volume which is generating that current. This is
%%mainly a visual resource for a better understanding of this project
function create_cylinder(H,R)
length_1=20;
length_2=100;
% Definition of vectors
angle = linspace(0,2*pi,length_2); 
z = linspace(0,H,length_1);

inverted_z=z';

% Create cylinder (only the lateral)
x_lat= repmat(R*cos(angle),length_1,1); 
y_lat= repmat(R*sin(angle),length_1,1);
z_lat= repmat(inverted_z,1,length_2);

% To close the ends
%Note: flipud will switch the vectors upside down, for example if we had
%(vertically) 1 3 5, we would get 5 3 1
X = [x_lat*0; flipud(x_lat); (x_lat(1,:))*0]; 
Y = [y_lat*0; flipud(y_lat); (y_lat(1,:))*0];
Z = [z_lat; flipud(z_lat); z_lat(1,:)];

% Draw cylinder
[number_surfaces,v]= surf2patch(X,Y,Z); hidden on; %Patch is to plot more than one polygon

%We will not give it full opacity so that it does not compromise the
%visualisation of the vectors generated by the quiver command in the
%following codes
patch('Vertices',v,'Faces',number_surfaces,'facecolor','b','facealpha',0.3,'edgealpha',0.3);
end